- fix error C2664: 'size_t libiconv(libiconv_t,const char **,size_t *,char **,size_t *)': cannot convert argument 2 from 'char **' to 'const char **' - fix Win32/MSVC compiler errors due to system header files (windows.h) defining min & max macros. - synchronized the MSVC premade config file with the master CMake one... - MSVC/Win32: fix Unicode build by using the ANSI Win32 API